version: "3.8"

services:
    server:
        image: ghcr.io/roseckyj/terratinker_server:latest
        expose:
            - 7070
        networks:
            default:
        restart: always
        environment:
            - EULA=${EULA:-false}
        volumes:
            - fileUpload:/app/server/plugins/TerraTinker
        deploy:
            mode: replicated
            replicas: 4

    manager:
        image: ghcr.io/roseckyj/terratinker_manager:latest
        expose:
            - 8080
        networks:
            default:
        restart: always
        environment:
            - PORT=8080
            - SERVER_URL=server:7070
        volumes:
            - fileUpload:/app/uploads

    web:
        image: ghcr.io/roseckyj/terratinker_web:latest
        ports:
            - ${PORT:-80}:${PORT:-80}
        networks:
            default:
        restart: always

volumes:
    fileUpload:
        driver: local
