version: "3.8"

services:
    server:
        image: ghcr.io/roseckyj/terratinker_server:latest
        expose:
            - 7070
        networks:
            default:
        restart: always
        environment:
            - EULA=${EULA:-false}
        volumes:
            - fileUpload:/app/plugins/TerraTinker

    web:
        image: ghcr.io/roseckyj/terratinker_web:latest
        expose:
            - ${PORT:-80}
        networks:
            default:
        restart: always
        links:
            - server
        labels: 
            - "traefik.http.routers.terratinker.rule=Host(`terratinker.xrosecky.cz`) || Host(`terratinker.fi.muni.cz`)"
            - "traefik.http.routers.terratinker.tls=true"
            - "traefik.http.routers.terratinker.tls.certresolver=lets-encrypt"
            - "traefik.http.services.terratinker.loadbalancer.server.port=${PORT:-80}"

volumes:
    fileUpload:
        driver: local