version: "3.8"

services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        expose:
            - 7070
        networks:
            default:
        restart: always
        environment:
            - EULA=${EULA}
        volumes:
            - fileUpload:/app/plugins/TerraTinker

    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        ports:
            - 80:80
        networks:
            default:
        restart: always
        links:
            - server

volumes:
    fileUpload:
        driver: local
