version: "3.8"

services:
    server:
        image: ghcr.io/roseckyj/terratinker_server:latest
        expose:
            - 7070
        networks:
            default:
        restart: always
        environment:
            - EULA=${EULA:-false}
        volumes:
            - fileUpload:/app/plugins/TerraTinker

    web:
        image: ghcr.io/roseckyj/terratinker_web:latest
        ports:
            - ${PORT:-80}:80
        networks:
            default:
        restart: always
        links:
            - server

volumes:
    fileUpload:
        driver: local
