version: "3.8"

services:
    server:
        image: ghcr.io/roseckyj/terratinker_server:latest
        expose:
            - 7070
        networks:
            default:
        restart: always
        environment:
            - EULA=${EULA:-false}
        volumes:
            - fileUpload:/app/server/plugins/TerraTinker
        deploy:
            mode: replicated
            replicas: 4

    manager:
        image: ghcr.io/roseckyj/terratinker_manager:latest
        expose:
            - 8080
        networks:
            default:
        restart: always
        environment:
            - PORT=8080
            - SERVER_URL=server:7070
        volumes:
            - fileUpload:/app/uploads

    web:
        image: ghcr.io/roseckyj/terratinker_web:latest
        expose:
            - ${PORT:-80}
        networks:
            default:
        restart: always
        labels:
            - "traefik.http.routers.terratinker.rule=Host(`terratinker.xrosecky.cz`) || Host(`terratinker.fi.muni.cz`)"
            - "traefik.http.routers.terratinker.tls=true"
            - "traefik.http.routers.terratinker.tls.certresolver=lets-encrypt"
            - "traefik.http.services.terratinker.loadbalancer.server.port=${PORT:-80}"

volumes:
    fileUpload:
        driver: local
